# Generated by Django 4.2.16 on 2024-09-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text',
            new_name='comment',
        ),
    ]
