# Generated by Django 4.2.16 on 2024-09-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_text_comments_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-pub_date']},
        ),
    ]
