# Generated by Django 4.2.16 on 2024-09-14 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
